name: number_game
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

flutter:

  uses-material-design: true


